name: Deploy Dockerized Node.js Service

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ secrets.DOCKER_USER }}/my-auth-app:latest .
          docker push ghcr.io/${{ secrets.DOCKER_PW }}/my-auth-app:latest

      - name: Deploy to remote server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/my-auth-app:latest:latest
            docker stop my-auth-app || true
            docker rm my-auth-app || true
            echo "USERNAME=${{ secrets.USERNAME }}" > .env
            echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
            echo "SECRET_MESSAGE=${{ secrets.SECRET_MESSAGE }}" >> .env
            docker run -d --env-file .env -p 3000:3000 --name node-secret-service ghcr.io/${{ secrets.DOCKERHUB_USERNAME }}/my-auth-app:latest:latest
